imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: @AppBundle/Resources/config/services.yml }
    - { resource: @AppBundle/Resources/config/widgets.yml }
    - { resource: @AppAdminBundle/Resources/config/admin.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale:                                             en
    assetic.filter.compass.bin:                         %compass_path%
    assetic.filter.compass.images_dir:                  %kernel.root_dir%/../web/bundles/app/img
    assetic.filter.compass.fonts_dir:                   %kernel.root_dir%/../web/bundles/app/fonts
    assetic.filter.compass.generated_images_path:       %kernel.root_dir%/../web/bundles/app/img
    assetic.filter.compass.http_path:                   /
    assetic.filter.compass.http_generated_images_path:  /bundles/app/img
    assetic.filter.compass.http_fonts_path:             /bundles/app/fonts
    web_dir:                                            %kernel.root_dir%/../web
    watermark_path:                                     %kernel.root_dir%/../web/img/watermark.png
    no_image:                                           img/no-image.png
    upload_img_directory:                               img/products
    sonata.user.admin.user.entity:                      AppBundle\Entity\Users
    sonata.user.admin.user.class:                       AppAdminBundle\Admin\UsersAdmin

framework:
    #esi:             ~
    translator:      { fallbacks: ["ru"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "ru"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.pdo
        gc_maxlifetime: 8640000
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    #exception_controller:  AppBundle:Exception:index
    globals:
        options: @options
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'

# Assetic Configuration
assetic:
    #write_to: %kernel.root_dir%/../web
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AppBundle, AppImportBundle, AppAdminBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        sass:    ~
        compass: ~
        uglifyjs2:
            # the path to the uglifyjs executable
            bin: "%kernel.root_dir%/../node_modules/.bin/uglifyjs.cmd"
        uglifycss:
            bin: "%kernel.root_dir%/../node_modules/.bin/uglifycss"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig


# Doctrine Configuration
doctrine:
    dbal:
        #default_connection: local
        default_connection: default
        connections:
            default:
                driver_class: AppBundle\DBAL\Driver
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  utf8
                mapping_types:
                    enum: string
            local:
                driver_class: AppBundle\DBAL\Driver
                driver:   pdo_mysql
                host:     192.168.0.88
                port:     "%database_port%"
                dbname:   mytex.local
                user:     mytex.local
                password: rezXYFqA7n6e3WTY
                charset:  utf8
                mapping_types:
                    enum: string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager:   default
        entity_managers:
            default:
                #connection:       local
                connection:       default
                mappings:
                    AppBundle: ~
                    AppAdminBundle: ~
                    FOSUserBundle: ~
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore

# Swiftmailer Configuration
#swiftmailer:
    #transport: gmail
    ##encryption: ssl
    ##auth_mode: login
    ##host:      smtp.gmail.com
    ##port:      465 or 587
    #username:  "mmyttexx@gmail.com"
    #password:  "Mytex-1000"
    #spool:
        #type: file
        #path: "%kernel.root_dir%/spool"
swiftmailer:
    transport: gmail
    username:  "mytex.com.ua@gmail.com"
    password:  "Mytex-33000"
    spool:
        type: file
        path: "%kernel.root_dir%/spool"
#swiftmailer:
    #transport: smtp
    #encryption: ssl
    #auth_mode: login
    #host:      smtp.googlemail.com
    #port:      465
    #username:  "33secundy@gmail.com"
    #password:  "zkp82d_ac"
    #spool:
        #type: file
        #path: "%kernel.root_dir%/spool"


sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
        # Your other blocks
        sonata.block.service.text:
        sonata.block.service.action:
        app.admin.block.import:

sonata_admin:
    title:      Admin
    title_logo: bundles/app/img/logo.png
    templates:
        layout:  AppAdminBundle:sonata_base_layout.html.twig
        #filter:           AppBundle:admin:filter_admin_fields.html.twig
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: left, type: app.admin.block.import}

sonata_translation:
    locales: [ru]
    default_locale: ru
    # here enable the types you need
    gedmo:
        enabled: true
    #phpcr:
    #    enabled: true

sonata_doctrine_orm_admin:
    templates:
        form: [ AppAdminBundle:admin:orm_form_admin_fields.html.twig ]
        #filter: [ SonataDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig ]

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\Users
    group:
        group_class: Sonata\UserBundle\Entity\BaseGroup

fos_elastica:
    clients:
        default: { host: 127.0.0.1, port: 9200 }
    indexes:
        app:
            client: default
            finder:
            types:
                products:
                    mappings:
                        productModels:
                            type: "object"
                            properties:
                                name:
                                    type: string
                        characteristicValues:
                            type: "object"
                            properties:
                                name:
                                    type: string
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Products
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~

liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: media/cache

    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/

    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null

    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction

    filter_sets:
        cache: ~
        mini:
            quality: 80
            filters:
                thumbnail: { size: [60, 60], mode: outbound}
        small:
            quality: 80
            filters:
                thumbnail: { size: [56, 82], mode: outbound}
        medium:
            quality: 80
            filters:
                thumbnail: { size: [360, 503], mode: outbound}
        large:
            quality: 80
            filters:
                thumbnail: { size: [680, 400], mode: inset}
        main_slider:
            quality: 80
            filters:
                thumbnail: { size: [843, 438], mode: inset}

# Social authentication
hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    connect:
        account_connector: users
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
            google: google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_app_id%"
            client_secret:       "%facebook_app_secret%"
            scope:               ""
        vkontakte:
            type:                vkontakte
            client_id:           "%vkontakte_app_id%"
            client_secret:       "%vkontakte_app_secret%"
            scope:               ""
    # here you will add one (or more) configurations for resource owners

knp_paginator:
    page_range: 4                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: ~          # sort field query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: AppBundle:partials:pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template