# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale:                                             ru
    assetic.filter.compass.bin:                         "%compass_path%"
    assetic.filter.compass.images_dir:                  "%kernel.root_dir%/../web/bundles/app/img"
    assetic.filter.compass.fonts_dir:                   "%kernel.root_dir%/../web/bundles/app/fonts"
    assetic.filter.compass.generated_images_path:       "%kernel.root_dir%/../web/bundles/app/img"
    assetic.filter.compass.http_path:                   /
    assetic.filter.compass.http_generated_images_path:  /bundles/app/img
    assetic.filter.compass.http_fonts_path:             /bundles/app/fonts
    web_dir:                                            "%kernel.root_dir%/../web"
    watermark_path:                                     "%kernel.root_dir%/../web/img/watermark.png"
    no_image:                                           img/no-image.png
    upload_img_directory:                               img/products
    upload_shares_img_directory:                        img/shares
    sonata.user.admin.user.entity:                      AppBundle\Entity\Users
    sonata.user.admin.user.class:                       AppAdminBundle\Admin\UsersAdmin
    orders.add_bonuses_days_interval:                   14

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@AppBundle/Resources/config/widgets.yml" }
    - { resource: "@UserBundle/Resources/config/config.yml" }
    - { resource: "@AppAdminBundle/Resources/config/admin.yml" }
    - { resource: mysql.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["ru"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "ru"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.pdo
        gc_maxlifetime: 8640000
    fragments:       ~
    http_method_override: true

# Recaptcha Configuration
ewz_recaptcha:
#    enabled: true
#    ajax: true
    public_key:  6LcBThwTAAAAAONvtJ8-xxl78jy6hWFiKOiUSPjC
    private_key: 6LcBThwTAAAAAONvtJ8-xxl78jy6hWFiKOiUSPjC
    locale_key:  '%kernel.default_locale%'

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
#    exception_controller:  AppBundle:Exception:index
    globals:
        options: "@options"
        cart: "@cart"
        humanizer: "@humanizer"
        prices: "@prices_calculator"
        fos_csrf_provider: "@form.csrf_provider"
        filters: "@filters"
        share: "@share"
        history_manager: "@history_manager"
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'

# Assetic Configuration
assetic:
    #write_to: %kernel.root_dir%/../web
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AppBundle, AppImportBundle, AppAdminBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        sass:    ~
        compass: ~
        uglifyjs2:
            # the path to the uglifyjs executable
            bin: "%kernel.root_dir%/../node_modules/.bin/uglifyjs.cmd"
        uglifycss:
            bin: "%kernel.root_dir%/../node_modules/.bin/uglifycss"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig


# Doctrine Configuration
doctrine:
    dbal:
        #default_connection: local
        default_connection: default
        connections:
            default:
                driver_class: AppBundle\DBAL\Driver
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  utf8
                mapping_types:
                    enum: string
            local:
                driver_class: AppBundle\DBAL\Driver
                driver:   pdo_mysql
                host:     192.168.0.88
                port:     "%database_port%"
                dbname:   mytex.local
                user:     mytex.local
                password: rezXYFqA7n6e3WTY
                charset:  utf8
                mapping_types:
                    enum: string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager:   default
        entity_managers:
            default:
                #connection:       local
                connection:       default
                mappings:
                    AppBundle: ~
                    AppAdminBundle: ~
                    FOSUserBundle: ~
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:
        type: file
        path: "%kernel.root_dir%/spool"

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
        # Your other blocks
        sonata.block.service.text:
        sonata.block.service.action:
        app.admin.block.import:

sonata_admin:
    title:      Sirius-sport
    title_logo: bundles/app/img/logo.png
    templates:
        layout: AppAdminBundle:sonata_base_layout.html.twig
        edit:   AppAdminBundle:edit.html.twig
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: left, type: app.admin.block.import}
    security:
        handler: sonata.admin.security.handler.role

sonata_translation:
    locales: [ru]
    default_locale: ru
    # here enable the types you need
    gedmo:
        enabled: true
    #phpcr:
    #    enabled: true

sonata_intl:
    timezone:
        # default timezone used as fallback
        default: Europe/Kiev

        # locale specific overrides
        locales:
            fr: Europe/Kiev

sonata_doctrine_orm_admin:
    templates:
        form: [ AppAdminBundle:admin:orm_form_admin_fields.html.twig ]
        #filter: [ SonataDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig ]

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\Users
    group:
        group_class: Sonata\UserBundle\Entity\BaseGroup
    registration:
        form:
            type: app_user_registration
            handler: app_user.form.handler.registration

fos_elastica:
    clients:
        default: { host: 127.0.0.1, port: 9200 }
    indexes:
        app:
            client: default
            finder:
            settings:
                index:
                    analysis:
                        analyzer:
                            my_analyzer:
                                type: custom
                                tokenizer: lowercase
                                filter   : [my_ngram]
                        filter:
                            my_ngram:
                                type: "nGram"
                                min_gram: 3
                                max_gram: 10
            types:
                products:
                    mappings:
                        name:
                            type: string
                            analyzer: my_analyzer
                        article:
                            type: string
                            analyzer: my_analyzer
                        content:
                            type: string
                            analyzer: my_analyzer
                        characteristics:
                            type: string
                            analyzer: my_analyzer
                        features:
                            type: string
                            analyzer: my_analyzer
                        active:
                            type: boolean
                        baseCategory:
                            type: "object"
                            properties:
                                name:
                                    type: string
                                    analyzer: my_analyzer
                        productModels:
                            type: "object"
                            properties:
                                productColors:
                                    type: "object"
                                    properties:
                                        name:
                                            type: string
                                            analyzer: my_analyzer
                                published:
                                    type: boolean
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Products
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~

liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../web"
                cache_prefix: media/cache

    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../web/"

    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null

    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction

    filter_sets:
        cache: ~
        mini:
            quality: 80
            filters:
                thumbnail: { size: [60, 60], mode: outbound}
                interlace:
                    # mode can be one of: 'none', 'line', 'plane' and 'partition'
                    mode: plane
        small:
            quality: 80
            filters:
                thumbnail: { size: [56, 82], mode: outbound}
                interlace:
                    # mode can be one of: 'none', 'line', 'plane' and 'partition'
                    mode: plane
        in_wholesale_cart:
            quality: 80
            filters:
                thumbnail: { size: [90, 87], mode: outbound}
                interlace:
                    # mode can be one of: 'none', 'line', 'plane' and 'partition'
                    mode: plane
        on_wholesale_cart_page:
            quality: 80
            filters:
                thumbnail: { size: [68, 87], mode: outbound}
                interlace:
                    # mode can be one of: 'none', 'line', 'plane' and 'partition'
                    mode: plane
        in_cart:
            quality: 80
            filters:
                thumbnail: { size: [155, 176], mode: outbound}
                interlace:
                    # mode can be one of: 'none', 'line', 'plane' and 'partition'
                    mode: plane
        medium:
            quality: 80
            filters:
                thumbnail: { size: [360, 503], mode: outbound}
                interlace:
                    # mode can be one of: 'none', 'line', 'plane' and 'partition'
                    mode: plane
        large:
            quality: 80
            filters:
                thumbnail: { size: [680, 400], mode: inset}
                interlace:
                    # mode can be one of: 'none', 'line', 'plane' and 'partition'
                    mode: plane
        main_slider:
            quality: 100
            filters:
                thumbnail: { size: [1920, 770 ], mode: inset}
                interlace:
                    # mode can be one of: 'none', 'line', 'plane' and 'partition'
                    mode: plane

# Social authentication
hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    connect:
        account_connector: users
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
            google: google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_app_id%"
            client_secret:       "%facebook_app_secret%"
            scope:               ""
        vkontakte:
            type:                vkontakte
            client_id:           "%vkontakte_app_id%"
            client_secret:       "%vkontakte_app_secret%"
            scope:               ""
    # here you will add one (or more) configurations for resource owners

knp_paginator:
    page_range: 4                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: ~          # sort field query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: AppBundle:partials:pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template