admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_profile_show:
    path: /user/profile
    defaults: { _controller: AppBundle:User:profile }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

app_import:
    resource: "@AppImportBundle/Resources/config/routing.yml"

# Admin
app_admin:
    resource: "@AppAdminBundle/Resources/config/routing.yml"

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin_login:
    pattern:  /admin/login
    defaults: { _controller: FOSUserBundle:Security:login }

admin_check:
    pattern:  /admin/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

admin_logout:
    pattern:  /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

app_yml:
    resource: "@AppBundle/Resources/config/routing.yml"

# Social authentication
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /login
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
hwi_oauth_connect_service:
    pattern: /login/service/{service}
    defaults: { _controller: AppBundle:Security:connectService}
facebook_login:
    path: /login/check-facebook
vkontakte_login:
    path: /login/check-vkontakte
login_after:
    pattern:  /after_login
    defaults: { _controller: AppBundle:Security:after }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix: /js/routing

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Because category route is "/{category}"
app_category:
    resource: "@AppBundle/Controller/ShopController.php"
    type:     annotation
app_product:
    resource: "@AppBundle/Controller/ProductController.php"
    type:     annotation