<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\ProductModelsHistory;

/**
 * ProductModelsHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductModelsHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param ProductModelsHistory $history
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function countOfNewestWithSameChanged(ProductModelsHistory $history)
    {
        return $this->createQueryBuilder('history')
            ->select('COUNT(history.id)')
            ->where('history.changeType = :changeType AND history.createTime > :createTime AND history.changed = :changed
                AND history.productModel = :product_model')
            ->setParameters([
                'changeType' => $history->getChangeType(),
                'createTime' => $history->getCreateTime(),
                'changed' => $history->getChanged(),
                'product_model' => $history->getProductModels()
            ])
            ->getQuery()
            ->getSingleScalarResult();
    }
}
