<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\ProductModelSpecificSizeHistory;

/**
 * ProductModelSpecificSizeHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductModelSpecificSizeHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param ProductModelSpecificSizeHistory $history
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function countOfNewestWithSameChanged(ProductModelSpecificSizeHistory $history)
    {
        return $this->createQueryBuilder('history')
            ->select('COUNT(history.id)')
            ->where('history.changeType = :changeType AND history.createTime > :createTime AND history.changed = :changed
                AND history.productModelSpecificSize = :product_model')
            ->setParameters([
                'changeType' => $history->getChangeType(),
                'createTime' => $history->getCreateTime(),
                'changed' => $history->getChanged(),
                'product_model' => $history->getProductModelSpecificSize()
            ])
            ->getQuery()
            ->getSingleScalarResult();
    }
}
