<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\ReturnProductHistory;

/**
 * ReturnProductHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReturnProductHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param ReturnProductHistory $history
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function countOfNewestWithSameChanged(ReturnProductHistory $history)
    {
        return $this->createQueryBuilder('history')
            ->select('COUNT(history.id)')
            ->where('history.changeType = :changeType AND history.createTime > :createTime AND history.changed = :changed
                AND history.returnProduct = :return_product')
            ->setParameters([
                'changeType' => $history->getChangeType(),
                'createTime' => $history->getCreateTime(),
                'changed' => $history->getChanged(),
                'return_product' => $history->getReturnProduct()
            ])
            ->getQuery()
            ->getSingleScalarResult();
    }
}
