<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\ReturnedSizesHistory;

/**
 * ReturnedSizesHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReturnedSizesHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param ReturnedSizesHistory $history
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function countOfNewestWithSameChanged(ReturnedSizesHistory $history)
    {
        return $this->createQueryBuilder('history')
            ->select('COUNT(history.id)')
            ->where('history.changeType = :changeType AND history.createTime > :createTime AND history.changed = :changed
                AND history.returnedSizes = :returned_sizes')
            ->setParameters([
                'changeType' => $history->getChangeType(),
                'createTime' => $history->getCreateTime(),
                'changed' => $history->getChanged(),
                'returned_sizes' => $history->getReturnedSizes()
            ])
            ->getQuery()
            ->getSingleScalarResult();
    }
}
