<?php

namespace AppBundle\Entity\Repository;

/**
 * ReturnProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReturnProductRepository extends \Doctrine\ORM\EntityRepository
{
}
