AppBundle\Entity\Users:
    properties:
        name:
            - NotBlank:
                message: acme_user.first_name.blank
                groups: [ "UserProfile" ]
        surname:
            - NotBlank:
                message: acme_user.surname.blank
                groups: [ "UserProfile" ]
        phone:
            - NotBlank:
                message: acme_user.phone.blank
                groups: [ "UserProfile" ]



# Note: We still want to validate the email
# See FOSUserBundle/Resources/config/validation/orm.xml to understand
# the UniqueEntity constraint that was originally applied to both
# username and email fields
#
# As you can see, we are only applying the UniqueEntity constraint to
# the email field and not the username field.
FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields: email
             errorPath: email
             message: fos_user.email.already_used
             groups: [ "UserRegistration", "UserProfile" ]

    properties:
        email:
            - Length:
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "UserRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "UserRegistration", "UserProfile" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "UserRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                max: 4096
                minMessage: fos_user.password.short
                groups: [ "UserRegistration", "UserProfile", "ResetPassword", "ChangePassword"]

FOS\UserBundle\Model\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "UserRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "UserRegistration" ]
