
wishlist:
    path:      /wishlist
    defaults:  { _controller: AppBundle:Wishlist:show }

form:
    path:     /form
    defaults: { _controller: AppBundle:Search:form}

search:
    path:     /search/{search}
    defaults: { _controller: AppBundle:Search:search }

