services:
    options:
        class: AppBundle\Services\Options
        arguments: ["@doctrine.orm.entity_manager"]
    entities:
        class: AppBundle\Services\Entities
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    sort:
        class: AppBundle\Services\Sort
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    users:
        class: AppBundle\Services\Users
        arguments: ['@fos_user.user_manager', { vkontakte: vkontakte_id }]
    cart:
        class: AppBundle\Services\Cart
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@session"]
    wishlist:
        class: AppBundle\Services\WishList
        arguments: ["@service_container", "@session"]
    compare:
        class: AppBundle\Services\Compare
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@session"]
    search:
        class: AppBundle\Services\Search
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    update_all:
        class: AppBundle\Services\UpdateAll
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    checkRelationship:
        class: AppBundle\Services\CheckRelationship
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    clearDb:
        class: AppBundle\Services\ClearDb
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    cron_mailer:
        class: AppBundle\Services\CronMailer
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    proc:
        class: AppBundle\Services\Proc
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "%kernel.root_dir%"]
    uploader:
        class: AppBundle\Services\Upload
        arguments: ["@service_container"]
    last_urls:
        class: AppBundle\Services\LastUrls
        arguments: ["@service_container", "@session"]
    request_listener:
        class: AppBundle\Event\RequestListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments: ["@service_container"]
    contract_bundle.listener.contract:
        class: AppBundle\Event\OrderListener
        arguments:
            templating: "@twig"
            mailer: "@mailer"
        tags:
            - { name: kernel.event_listener, event: order.created, method: onOrderCreated }