services:
    options:
        class: AppBundle\Services\Options
        arguments: ["@doctrine.orm.entity_manager", "@cache"]
    entities:
        class: AppBundle\Services\Entities
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    sort:
        class: AppBundle\Services\Sort
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    users:
        class: AppBundle\Services\Users
        arguments: ['@fos_user.user_manager', { vkontakte: vkontakte_id, facebook: facebook_id }]
    cart_factory:
        class: AppBundle\Factory\CartFactory
        arguments: ["@service_container"]
    cart:
        class: AppBundle\Services\Cart
        factory: [@cart_factory, createCart]
        arguments: ["@session_cart_store"]
    session_cart_store:
        class: AppBundle\Cart\Store\SessionCartStore
        arguments: [@session]
    order:
        class: AppBundle\Services\Order
        arguments: [@doctrine.orm.entity_manager, @service_container]
    product:
        class: AppBundle\Services\Product
        arguments: [@doctrine.orm.entity_manager, @service_container]
    return_product:
        class: AppBundle\Services\ReturnProduct
        arguments: [@doctrine.orm.entity_manager, @service_container]
    returned_sizes:
        class: AppBundle\Services\ReturnedSizes
        arguments: [@doctrine.orm.entity_manager, @service_container]
    share:
        class: AppBundle\Services\Share
        arguments: [@service_container, @doctrine.orm.entity_manager]
    share_group_listener:
        class: AppBundle\Listener\ShareGroupListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_subscriber }
    decrement_sizes_quantity:
        class: AppBundle\Listener\ChangeSizesQuantity
        arguments: [@service_container]
        tags:
            - { name: kernel.event_subscriber }
    subscriber.change_user_total_spent:
        class: AppBundle\Listener\ChangeUserTotalSpentSubscriber
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }
    filters:
        class: AppBundle\Services\Filters
        arguments: ["@service_container"]
    wishlist:
        class: AppBundle\Services\WishList
        arguments: ["@service_container", "@session"]
    compare:
        class: AppBundle\Services\Compare
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@session"]
    search:
        class: AppBundle\Services\Search
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    distribution:
        class: AppBundle\Services\Distribution
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    update_all:
        class: AppBundle\Services\UpdateAll
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    checkRelationship:
        class: AppBundle\Services\CheckRelationship
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    clearDb:
        class: AppBundle\Services\ClearDb
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    proc:
        class: AppBundle\Services\Proc
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "%kernel.root_dir%"]
    uploader:
        class: AppBundle\Services\Upload
        arguments: ["@service_container"]
    last_urls:
        class: AppBundle\Services\LastUrls
        arguments: ["@service_container", "@session"]
    humanizer:
        class: AppBundle\Services\Humanizer
        arguments: ["@service_container"]
    prices_calculator_factory:
        class: AppBundle\Factory\PricesCalculatorFactory
    prices_calculator:
        class: AppBundle\Services\PricesCalculator
        factory: [@prices_calculator_factory, createPricesCalculator]
        arguments: [@service_container, @doctrine.orm.entity_manager, @security.token_storage]
    history_manager:
        class: AppBundle\Services\HistoryManager
        arguments: [@service_container, @doctrine.orm.entity_manager]
    response_listener:
        class: AppBundle\Listener\ResponseListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    request_listener:
        class: AppBundle\Listener\RequestListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    app.subscriber.bonuses:
        class: AppBundle\Listener\BonusesAdder
        arguments: ["@order"]
        tags:
            - { name: kernel.event_listener, event: app.order_canceled, method: onOrderCanceled }
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments: ["@service_container"]

    novaposhta:
        class: AppBundle\Services\NovaPoshta
        arguments: ["@doctrine.orm.entity_manager"]

    app.form.create_order:
        class: AppBundle\Form\Type\CreateOrderType
        arguments: ['@prices_calculator', '@service_container']
        tags:
            - { name: form.type }

    return_validator1:
        class: AppBundle\Validator\ReturnOrderNumConstraintValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator }

    return_validator2:
        class: AppBundle\Validator\ReturnUserPhoneConstraintValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator }

    invoice_transformer:
        class: AppBundle\Services\InvoiceTransformer
        arguments: [@service_container]

    num_to_string:
        class: AppBundle\Services\NumToString
