services:
    options:
        class: AppBundle\Services\Options
        arguments: ["@doctrine.orm.entity_manager"]
    entities:
        class: AppBundle\Services\Entities
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    sort:
        class: AppBundle\Services\Sort
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    users:
        class: AppBundle\Services\Users
        arguments: ['@fos_user.user_manager', { vkontakte: vkontakte_id, facebook: facebook_id }]
    cart_factory:
        class: AppBundle\Factory\CartFactory
        arguments: ["@service_container"]
    cart:
        class: AppBundle\Services\Cart
        factory: [@cart_factory, createCart]
        arguments: ["@doctrine.orm.entity_manager", "@session"]
    order:
        class: AppBundle\Services\Order
        arguments: [@doctrine.orm.entity_manager, @service_container]
    share:
        class: AppBundle\Services\Share
        arguments: [@service_container, @doctrine.orm.entity_manager]
    share_group_listener:
        class: AppBundle\Listener\ShareGroupListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_subscriber }
    filters:
        class: AppBundle\Services\Filters
        arguments: ["@service_container"]
    wishlist:
        class: AppBundle\Services\WishList
        arguments: ["@service_container", "@session"]
    compare:
        class: AppBundle\Services\Compare
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@session"]
    search:
        class: AppBundle\Services\Search
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    update_all:
        class: AppBundle\Services\UpdateAll
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    checkRelationship:
        class: AppBundle\Services\CheckRelationship
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    clearDb:
        class: AppBundle\Services\ClearDb
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    cron_mailer:
        class: AppBundle\Services\CronMailer
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    proc:
        class: AppBundle\Services\Proc
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "%kernel.root_dir%"]
    uploader:
        class: AppBundle\Services\Upload
        arguments: ["@service_container"]
    last_urls:
        class: AppBundle\Services\LastUrls
        arguments: ["@service_container", "@session"]
    humanizer:
        class: AppBundle\Services\Humanizer
        arguments: ["@service_container"]
    prices_calculator:
        class: AppBundle\Services\PricesCalculator
        arguments: [@service_container, @doctrine.orm.entity_manager]
    history_manager:
        class: AppBundle\Services\HistoryManager
        arguments: [@service_container, @doctrine.orm.entity_manager]
    response_listener:
        class: AppBundle\Listener\ResponseListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    request_listener:
        class: AppBundle\Listener\RequestListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments: ["@service_container"]
    novaposhta:
        class: AppBundle\Services\NovaPoshta
        arguments: ["@doctrine.orm.entity_manager"]

    app.form.create_order:
        class: AppBundle\Form\Type\CreateOrderType
        arguments: ['@prices_calculator', '@service_container']
        tags:
            - { name: form.type }
