services:
    widgets.users:
        class: AppBundle\Widgets\Users
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@session"]
    widgets.sliders:
        class: AppBundle\Widgets\Sliders
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    widgets.menus:
        class: AppBundle\Widgets\Menus
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    widgets.breadcrumbs:
        class: AppBundle\Widgets\Breadcrumbs
        arguments: ["@service_container"]
    widgets.products:
        class: AppBundle\Widgets\Products
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]