AppBundle\Entity\SkuProducts:
    skuFor{1..19150}:
        sku:                  <ean8()>
        name:                 <sentence($nbWords = 3)>
        price:                <randomFloat($nbMaxDecimals = 2, $min = 0, $max = 1000)>
        quantity:             <numberBetween(0, 10)>
        vendors:              @vendors1
        productModels:        <numberBetween(1, 19150)>
        createTime:           <dateTimeBetween('now', 'now')>
        updateTime:           <dateTimeBetween('now', 'now')>
    sku{1..19150}:
        sku:                  <ean8()>
        name:                 <sentence($nbWords = 3)>
        price:                <randomFloat($nbMaxDecimals = 2, $min = 0, $max = 1000)>
        quantity:             <numberBetween(0, 10)>
        vendors:              @vendors<numberBetween(2, 4)>
        productModels:        <numberBetween(1, 19150)>
        createTime:           <dateTimeBetween('now', 'now')>
        updateTime:           <dateTimeBetween('now', 'now')>
