AppBundle\Entity\ActionLabels:
    type: entity
    table: action_labels
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
        name_UNIQUE:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        htmlClass:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: html_class
    lifecycleCallbacks: {  }
