AppBundle\Entity\Cities:
    type: entity
    table: cities
    indexes:
        fk_cities_carriers1_idx:
            columns:
                - carriers_id
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        carriers:
            targetEntity: Carriers
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                carriers_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
