AppBundle\Entity\DistributionSmsInfo:
    type: entity
    manyToOne:
        distribution:
            targetEntity: EmailAndSmsDistribution
            cascade: { }
            fetch: LAZY
            mappedBy: null
            inversedBy: smsInfos
            orphanRemoval: false
        users:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            joinColumns:
                users_id:
                    referencedColumnName: id
            orphanRemoval: false