AppBundle\Entity\Filters:
    type: entity
    table: filters
    indexes:
        text:
            columns:
                - name
    uniqueConstraints:
        ID_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        createTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            column: update_time
    manyToMany:
        characteristics:
            targetEntity: Characteristics
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: filters
            joinTable:
                name: filters_has_characteristics
                joinColumns:
                    -
                        name: filters_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: characteristics_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
