AppBundle\Entity\History:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
      name: discr
      type: string
    discriminatorMap:
      history: History
      order_history: OrderHistory
      product_models_history: ProductModelsHistory
      product_models_specific_size_history: ProductModelSpecificSizeHistory
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createTime:
            type: datetime
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        changeType:
            type: string
        changed:
            type: string
            nullable: true
        from:
            type: string
            nullable: true
            column: change_from
        to:
            type: string
            nullable: true
            column: change_to
        additional:
            type: text
            nullable: true
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            inversedBy: history
            joinColumns:
                user_id:
                    nullable: true
    lifecycleCallbacks: {  }
