AppBundle\Entity\MainBanners:
    type: entity
    table: main_banners
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        titleButton:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        alias:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        picture:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        priority:
            type: integer
            nullable: true
            options:
                unsigned: false
        active:
            type: boolean
            nullable: true
        wide:
            type: boolean
            nullable: true
        createTime:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: update_time
    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]