AppBundle\Entity\Menu:
    type: entity
    table: menu
    indexes:
        index:
            columns:
                - name
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
        name_UNIQUE:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        title:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    oneToMany:
        items:
            targetEntity: MenuItems
            cascade: {  }
            fetch: LAZY
            mappedBy: menu
            inversedBy: null
            orphanRemoval: true
    lifecycleCallbacks: {  }
