AppBundle\Entity\NovaposhtaSender:
    type: entity
    table: novaposhta_sender
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
            column: name
        ref:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
            column: ref
        firstName:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: last_name
        middleName:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
            column: middle_name
        email:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
            column: email
        phone:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: phone
    manyToOne:
        city:
            targetEntity: Cities
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                city_id:
                    referencedColumnName: id
            orphanRemoval: false
        warehouse:
            targetEntity: Stores
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                warehouse_id:
                    referencedColumnName: id
            orphanRemoval: false
