AppBundle\Entity\OrderStatus:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        code:
            type: string
            length: 255
        description:
            type: string
            length: 255
            nullable: true
        baseFlag:
            type: boolean
            column: base_flag
    lifecycleCallbacks: {  }
