AppBundle\Entity\Orders:
    type: entity
    table: orders
    repositoryClass: AppBundle\Entity\Repository\OrdersRepository
    indexes:
        fk_call_back_users1_idx:
            columns:
                - users_id
        type:
            columns:
                - type
        fk_orders_carriers1_idx:
            columns:
                - carriers_id
        fk_orders_cities1_idx:
            columns:
                - cities_id
        fk_orders_stores1_idx:
            columns:
                - stores_id
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        customDelivery:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: custom_delivery
        comment:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        comment_admin:
            type: text
            nullable: true
        fio:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        ttn:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        customTtn:
            type: text
            nullable: true
        phone:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 45м категорія
        pay:
            type: integer
            nullable: true
        additionalSolarDescription:
            type: string
            nullable: true
            length: 128
        additionalSolar:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            options:
                default: 0.00
        individualDiscount:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            options:
                default: 0.00
            column: individual_discount
        loyalityDiscount:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            options:
                default: 0.00
            column: loyality_discount
        upSellDiscount:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            options:
                default: 0.00
        bonuses:
            type: integer
            nullable: false
            options:
                default: 0
        bonusesEnrolled:
            type: boolean
            nullable: false
            options:
                default: false
        clientSmsId:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: client_sms_id
        clientSmsStatus:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: client_sms_status
        managerSmsId:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: manager_sms_id
        managerSmsStatus:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: manager_sms_status
        preOrderFlag:
            type: boolean
            options:
                default: false
        createTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            column: update_time
        doneTime:
            type: datetime
            nullable: true
    oneToMany:
        sizes:
            targetEntity: OrderProductSize
            cascade: [ all ]
            fetch: LAZY
            mappedBy: order
            inversedBy: null
            orphanRemoval: true
        history:
            targetEntity: OrderHistory
            cascade: [ all ]
            fetch: LAZY
            mappedBy: order
            inversedBy: null
            orderBy: {id: DESC}
        smsInfo:
            targetEntity: OrderSmsInfo
            cascade: [ all ]
            fetch: LAZY
            mappedBy: order
            orphanRemoval: true
    manyToOne:
        relatedOrder:
            targetEntity: Orders
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            orphanRemoval: false
        users:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            inversedBy: orders
            joinColumns:
                users_id:
                    referencedColumnName: id
            orphanRemoval: false
        status:
            targetEntity: OrderStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: orders
            inversedBy: null
            orphanRemoval: false
        payStatus:
            targetEntity: OrderStatusPay
            cascade: {  }
            fetch: LAZY
            mappedBy: orders
            inversedBy: null
            orphanRemoval: false
        carriers:
            targetEntity: Carriers
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                carriers_id:
                    referencedColumnName: id
            orphanRemoval: false
        cities:
            targetEntity: Cities
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cities_id:
                    referencedColumnName: id
            orphanRemoval: false
        stores:
            targetEntity: Stores
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                stores_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
