AppBundle\Entity\Pages:
    type: entity
    table: pages
    indexes:
        index:
            columns:
                - update_time
                - create_time
        text:
            columns:
                - title
                - alias
                - seo_title
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
        alias_UNIQUE:
            columns:
                - alias
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        alias:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        content:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        seoTitle:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: seo_title
        seoDescription:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: seo_description
        seoKeywords:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: seo_keywords
        createTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            column: update_time
    lifecycleCallbacks: {  }
