AppBundle\Entity\ProductModelImage:
    type: entity
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        link:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
                comment: aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d.png
        priority:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: 0
        createTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            column: update_time
    manyToOne:
        model:
            targetEntity: ProductModels
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: images
            orphanRemoval: false
    lifecycleCallbacks: {  }
