AppBundle\Entity\ProductColors:
    type: entity
    table: product_colors
    repositoryClass: AppBundle\Entity\Repository\ProductColorsRepository
    indexes:
        name:
            columns:
                - name
        hex:
            columns:
                - hex
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        hex:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        createTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            column: update_time
    oneToMany:
        models:
            targetEntity: ProductModels
            cascade: { }
            fetch: LAZY
            mappedBy: productColors
    lifecycleCallbacks: {  }
