AppBundle\Entity\ProductModels:
    type: entity
    table: product_models
    repositoryClass: AppBundle\Entity\Repository\ProductModelsRepository
    indexes:
        index:
            columns:
                - price
        fk_product_models_products1_idx:
            columns:
                - products_id
        fk_product_models_product_colors1_idx:
            columns:
                - product_colors_id
        name:
            columns:
                - name
        price:
            columns:
                - price
        oldprice:
            columns:
                - oldprice
        wholesale_price:
            columns:
                - price
        wholesale_oldprice:
            columns:
                - oldprice
        stock:
            columns:
                - in_stock
        priority:
            columns:
                - priority
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
        alias_UNIQUE:
            columns:
                - alias
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        alias:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        price:
            type: decimal
            nullable: true
            precision: 8
            scale: 2
            options:
                default: 0.00
        oldprice:
            type: decimal
            nullable: true
            precision: 8
            scale: 2
        wholesalePrice:
            type: decimal
            precision: 8
            scale: 2
            options:
                default: 0.00
        preOrderFlag:
            type: boolean
            options:
                default: false
        seoTitle:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: seo_title
        seoDescription:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: seo_description
        seoKeywords:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: seo_keywords
        content:
            type: text
            nullable: true
        characteristics:
            type: text
            nullable: true
        features:
            type: text
            nullable: true
        priority:
            type: integer
            nullable: true
            options:
                unsigned: false
        status:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        active:
            type: boolean
            nullable: true
        inStock:
            type: boolean
            nullable: true
            column: in_stock
        published:
            type: boolean
            nullable: true
        createTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            column: update_time
    oneToMany:
        productModelImages:
            targetEntity: ProductModelImages
            cascade: ["persist"]
            fetch: EAGER
            mappedBy: productModels
            inversedBy: null
            orphanRemoval: true
            orderBy: {  }
        skuProducts:
            targetEntity: SkuProducts
            cascade: ["all"]
            fetch: EAGER
            mappedBy: productModels
            inversedBy: productModels
            orphanRemoval: true
    manyToOne:
        productColors:
            targetEntity: ProductColors
            cascade: {  }
            fetch: EAGER
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_colors_id:
                    referencedColumnName: id
            orphanRemoval: false
        decorationColor:
            targetEntity: ProductColors
            cascade: {  }
            fetch: EAGER
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_model_decoration_color_id:
                    referencedColumnName: id
            orphanRemoval: false
        products:
            targetEntity: Products
            cascade: {  }
            fetch: EAGER
            mappedBy: null
            inversedBy: productModels
            joinColumns:
                products_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        sizes:
            targetEntity: ProductModelSizes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: productModels
            joinTable:
                name: product_models_has_sizes
                joinColumns:
                    -
                        name: product_model_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: size_id
                        referencedColumnName: id
            orderBy:
                size: ASC

    lifecycleCallbacks:
        prePersist: [ checkPrice, checkColor ]
        preUpdate:  [ checkPrice, checkColor ]
