AppBundle\Entity\ProductModelImages:
    type: entity
    table: product_model_images
    repositoryClass: AppBundle\Entity\Repository\ProductModelImagesRepository
    indexes:
        link:
            columns:
                - link
        fk_product_images_product_models1_idx:
            columns:
                - product_models_id
        thumbnail:
            columns:
                - thumbnail
        priority:
            columns:
                - priority
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    properties:
        file:
            - File:
                maxSize: 6000000
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        link:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
                comment: aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d.png
        thumbnail:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
                comment: aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d.png
        priority:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        createTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            column: update_time
    manyToOne:
        productModels:
            targetEntity: ProductModels
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: productModelImages
            joinColumns:
                product_models_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
