AppBundle\Entity\ProductModels:
    type: entity
    table: product_models
    repositoryClass: AppBundle\Entity\Repository\ProductModelsRepository
    indexes:
        index:
            columns:
                - price
        fk_product_models_products1_idx:
            columns:
                - products_id
        fk_product_models_product_colors1_idx:
            columns:
                - product_colors_id
        price:
            columns:
                - price
        wholesale_price:
            columns:
                - price
        stock:
            columns:
                - in_stock
        priority:
            columns:
                - priority
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
        alias_UNIQUE:
            columns:
                - alias
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        alias:
            type: string
            nullable: false
        price:
            type: decimal
            nullable: true
            precision: 8
            scale: 2
            options:
                default: 0.00
        wholesalePrice:
            type: decimal
            precision: 8
            scale: 2
            options:
                default: 0.00
        preOrderFlag:
            type: boolean
            options:
                default: false
        priority:
            type: integer
            nullable: true
            options:
                unsigned: false
        status:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        active:
            type: boolean
            nullable: true
        inStock:
            type: boolean
            nullable: true
            column: in_stock
        createTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            column: update_time
    oneToMany:
        sizes:
            targetEntity: ProductModelSpecificSize
            cascade: ["all"]
            fetch: LAZY
            mappedBy: model
            inversedBy: null
            orphanRemoval: true
        images:
            targetEntity: ProductModelImage
            cascade: ["persist"]
            fetch: LAZY
            mappedBy: model
            inversedBy: null
            orphanRemoval: true
            orderBy: {priority: ASC}
    manyToOne:
        productColors:
            targetEntity: ProductColors
            cascade: {  }
            fetch: EAGER
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_colors_id:
                    referencedColumnName: id
            orphanRemoval: false
        decorationColor:
            targetEntity: ProductColors
            cascade: {  }
            fetch: EAGER
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_model_decoration_color_id:
                    referencedColumnName: id
            orphanRemoval: false
        products:
            targetEntity: Products
            cascade: {  }
            fetch: EAGER
            mappedBy: null
            inversedBy: productModels
            joinColumns:
                products_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist: [ checkPrice, checkColor ]
        preUpdate:  [ checkPrice, checkColor ]
