AppBundle\Entity\Products:
    type: entity
    table: products
    repositoryClass: AppBundle\Entity\Repository\ProductsRepository
    indexes:
        fk_products_action_labels1_idx:
            columns:
                - action_labels_id
        status:
            columns:
                - status
        active:
            columns:
                - active
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        article:
            type: string
            nullable: false
        seoTitle:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: seo_title
        seoDescription:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: seo_description
        seoKeywords:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: seo_keywords
        content:
            type: text
            nullable: true
        characteristics:
            type: text
            nullable: true
        features:
            type: text
            nullable: true
        price:
            type: decimal
            nullable: true
            precision: 8
            scale: 2
            options:
                default: 0.00
        wholesalePrice:
            type: decimal
            precision: 8
            scale: 2
            options:
                default: 0.00
        quantity:
            type: integer
            options:
                default: 0
        status:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        active:
            type: boolean
            nullable: true
        createTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            column: update_time
    oneToMany:
        productModels:
            targetEntity: ProductModels
            cascade: ["all"]
            fetch: LAZY
            mappedBy: products
            inversedBy: null
            orphanRemoval: true
    manyToOne:
        actionLabels:
            targetEntity: ActionLabels
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                action_labels_id:
                    referencedColumnName: id
            orphanRemoval: false
        baseCategory:
            targetEntity: Categories
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                base_category_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:

        characteristicValues:
            targetEntity: CharacteristicValues
            cascade: ["persist"]
            fetch: LAZY
            mappedBy: null
            inversedBy: products
            joinTable:
                name: products_has_characteristic_values
                joinColumns:
                    -
                        name: products_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: characteristic_values_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks:
        prePersist: [ setFirstBaseCategory ]
