AppBundle\Entity\ShareSizesGroupDiscount:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        discount:
            type: integer
    manyToOne:
        shareGroup:
            targetEntity: ShareSizesGroup
            fetch: EAGER
            inversedBy: discounts
            joinColumn:
                onDelete: CASCADE
        companion:
            targetEntity: ShareSizesGroup
            fetch: EAGER
            inversedBy: discountCompanions
            joinColumn:
                onDelete: CASCADE
    lifecycleCallbacks: {  }
