AppBundle\Entity\ShareSizesGroup:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\Repository\ShareSizesGroupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        discount:
            type: decimal

    manyToOne:
        share:
            targetEntity: Share
            cascade: {  }
            fetch: EAGER
            mappedBy: null
            inversedBy: sizesGroups
            orphanRemoval: false
    oneToMany:
        actualModelSpecificSizes:
            targetEntity: ProductModelSpecificSize
            mappedBy: shareGroup
            fetch: LAZY
        discounts:
            targetEntity: ShareSizesGroupDiscount
            mappedBy: shareGroup
            fetch: LAZY
        discountCompanions:
            targetEntity: ShareSizesGroupDiscount
            mappedBy: companion
            fetch: LAZY
    manyToMany:
        sizes:
            targetEntity: ProductModelSizes
            fetch: LAZY
        characteristicValues:
            targetEntity: CharacteristicValues
            fetch: LAZY
        colors:
            targetEntity: ProductColors
            fetch: LAZY
        modelSpecificSizes:
            targetEntity: ProductModelSpecificSize
            mappedBy: shareGroups
            fetch: LAZY
    lifecycleCallbacks: {  }
