AppBundle\Entity\Share:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\Repository\ShareRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        class_name:
            type: string
            nullable: true
        image:
            type: string
        createTime:
            type: datetime
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        priority:
            type: integer
        status:
            type: boolean
        startTime:
            type: datetime
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        endTime:
            type: datetime
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    oneToMany:
        sizesGroups:
            targetEntity: ShareSizesGroup
            cascade: ["all"]
            fetch: LAZY
            mappedBy: share
            inversedBy: null
            orphanRemoval: true
    lifecycleCallbacks: {  }
