AppBundle\Entity\SkuProducts:
    type: entity
    table: sku_products
    repositoryClass: AppBundle\Entity\Repository\SkuProductsRepository
    indexes:
        index:
            columns:
                - price
                - sku
        fk_sku_products_product_models1_idx:
            columns:
                - product_models_id
        fk_sku_products_vendors1_idx:
            columns:
                - vendors_id
        count:
            columns:
                - quantity
        name:
            columns:
                - name
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sku:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        status:
            type: boolean
            options:
                unsigned: false
                default: false
        active:
            type: boolean
            nullable: true
        price:
            type: decimal
            nullable: true
            precision: 8
            scale: 2
            options:
                default: 0.00
        wholesale_price:
            type: decimal
            nullable: true
            precision: 8
            scale: 2
            options:
                default: 0.00
        quantity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: 0
        createTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            column: update_time
    manyToOne:
        productModels:
            targetEntity: ProductModels
            cascade: {  }
            #cascade: ["all"]
            fetch: EAGER
            mappedBy: null
            inversedBy: skuProducts
            joinColumns:
                product_models_id:
                    referencedColumnName: id
            orphanRemoval: false
        vendors:
            targetEntity: Vendors
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                vendors_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
