AppBundle\Entity\Stores:
    type: entity
    table: stores
    indexes:
        fk_stores_cities1_idx:
            columns:
                - cities_id
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        ref:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        fullJson:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        active:
            type: boolean
            nullable: true
    manyToOne:
        cities:
            targetEntity: Cities
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cities_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
