AppBundle\Entity\Unisender:
    type: entity
    table: unisender
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        phones:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        apiKey:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: api_key
        senderName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: sender_name
        active:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
