AppBundle\Entity\Users:
    type: entity
    table: users
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uid:
            type: integer
            nullable: true
            options:
                unsigned: false
        fio:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        phone:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        createTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            column: update_time
    lifecycleCallbacks: {  }
