AppBundle\Entity\Users:
    type: entity
    table: users
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uid:
            type: integer
            nullable: true
            options:
                unsigned: false
        facebook_id:
            type: string
            nullable: true
            length: 255
        facebook_access_token:
            type: string
            nullable: true
            length: 255
        vkontakte_id:
            type: string
            nullable: true
            length: 255
        vkontakte_access_token:
            type: string
            nullable: true
            length: 255
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        surname:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        middlename:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: middle_name
        phone:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        counterpartyRef:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: counterparty_ref
        createTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            column: update_time
    lifecycleCallbacks: {  }
