AppBundle\Entity\Wishlist:
    type: entity
    table: wishlist
    indexes:
        fk_call_back_users1_idx:
            columns:
                - users_id
        fk_wishlist_product_models1_idx:
            columns:
                - product_models_id
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        status:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        createTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            columnDefinition: TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            column: update_time
    manyToOne:
        users:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                users_id:
                    referencedColumnName: id
            orphanRemoval: false
        productModels:
            targetEntity: ProductModels
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_models_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
