services:
    app.admin.orders:
        class: AppAdminBundle\Admin\OrdersAdmin
        arguments: [~, AppBundle\Entity\Orders, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Заказы"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.cart:
        class: AppAdminBundle\Admin\CartAdmin
        arguments: [~, AppBundle\Entity\Cart, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Список всех заказанных товаров"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.cart_product_size:
        class: AppAdminBundle\Admin\CartProductSizeAdmin
        arguments: [~, AppBundle\Entity\CartProductSize, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Список всех заказанных товаров"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.categories:
        class: AppAdminBundle\Admin\CategoriesAdmin
        #arguments: [~, AppBundle\Entity\Categories, AppAdminBundle:CategoriesAdmin]
        arguments: [~, AppBundle\Entity\Categories, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Категории"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]
            #- [ setTemplate, [base_edit_form_macro, AppAdminBundle:admin:base_edit_form_macro.html.twig]]

    app.admin.filters:
        class: AppAdminBundle\Admin\FiltersAdmin
        arguments: [~, AppBundle\Entity\Filters, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Фильтры"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.products:
        class: AppAdminBundle\Admin\ProductsAdmin
        arguments: [~, AppBundle\Entity\Products, AppAdminBundle:CRUD, @service_container]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Товары"}
        calls:
            - [ addChild, [@app.admin.product_images, @app.admin.product_model_specific_size] ]
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]
            - [ setTemplate, [edit, AppAdminBundle:admin:product_models_edit.html.twig]]

    app.admin.product_models:
        class: AppAdminBundle\Admin\ProductModelsAdmin
        arguments: [~, AppBundle\Entity\ProductModels, AppAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Модели"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]
            - [ setTemplate, [form, AppAdminBundle:admin:form_admin_fields.html.twig]]
            - [ setTemplate, [edit, AppAdminBundle:admin:product_models_edit.html.twig]]

    app.admin.product_images:
        class: AppAdminBundle\Admin\ProductImagesAdmin
        arguments: [~, AppBundle\Entity\ProductImages, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Меню", label: "Изображения продуктов"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.product_model_specific_size:
        class: AppAdminBundle\Admin\ProductModelSpecificSizeAdmin
        arguments: [~, AppBundle\Entity\ProductModelSpecificSize, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.characteristics:
        class: AppAdminBundle\Admin\CharacteristicsAdmin
        arguments: [~, AppBundle\Entity\Characteristics, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Характеристики"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.characteristic_values:
        class: AppAdminBundle\Admin\CharacteristicValuesAdmin
        arguments: [~, AppBundle\Entity\CharacteristicValues, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Значения характеристик"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.product_colors:
        class: AppAdminBundle\Admin\ProductColorsAdmin
        arguments: [~, AppBundle\Entity\ProductColors, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Цвета товаров"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.product_model_sizes:
        class: AppAdminBundle\Admin\ProductModelSizesAdmin
        arguments: [~, AppBundle\Entity\ProductModelSizes, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Размеры товаров"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.vendors:
        class: AppAdminBundle\Admin\VendorsAdmin
        arguments: [~, AppBundle\Entity\Vendors, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Поставщики"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app_admin.admin.main_slider:
        class: AppAdminBundle\Admin\MainSliderAdmin
        arguments: [~, AppBundle\Entity\MainSlider, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление сайтом", label: "Слайдер главной страницы"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.pages:
        class: AppAdminBundle\Admin\PageAdmin
        arguments: [~, AppBundle\Entity\Pages, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Управление сайтом", label: "Статические страницы" }
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.site_params:
        class: AppAdminBundle\Admin\SiteParamsAdmin
        arguments: [~, AppBundle\Entity\SiteParams, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление сайтом", label: "Параметры"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.call_back:
        class: AppAdminBundle\Admin\CallBackAdmin
        arguments: [~, AppBundle\Entity\CallBack, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Запросы на перезвон"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.menu:
        class: AppAdminBundle\Admin\MenuAdmin
        arguments: [~, AppBundle\Entity\Menu, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Меню", label: "Меню"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.menu_items:
        class: AppAdminBundle\Admin\MenuItemsAdmin
        arguments: [~, AppBundle\Entity\MenuItems, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Меню", label: "Элементы меню"}
        calls:
            - [ setTranslationDomain, [AppAdminBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]

    app.admin.import:
        class: AppAdminBundle\Admin\ImportAdmin
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@validator"]

    app.admin.block.import:
        class: AppAdminBundle\Block\ImportBlockService
        arguments: [ "app.admin.block.import:", @templating ]
        tags:
            - { name: sonata.block }

    app_admin.admin.main_banners:
        class: AppAdminBundle\Admin\MainBannersAdmin
        arguments: [~, AppBundle\Entity\MainBanners, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление сайтом", label: "Банеры главной страницы"}