services:
    app.admin.new_orders:
        class: AppAdminBundle\Admin\NewOrdersAdmin
        arguments: [~, AppBundle\Entity\Orders, AppAdminBundle:Order]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Новые заказы"}

    app.admin.accepted_orders:
        class: AppAdminBundle\Admin\AcceptedOrdersAdmin
        arguments: [~, AppBundle\Entity\Orders, AppAdminBundle:Order]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Принятые заказы"}

    app.admin.wait_orders:
        class: AppAdminBundle\Admin\WaitOrdersAdmin
        arguments: [~, AppBundle\Entity\Orders, AppAdminBundle:Order]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Ожидающие заказы"}

    app.admin.formed_orders:
        class: AppAdminBundle\Admin\FormedOrdersAdmin
        arguments: [~, AppBundle\Entity\Orders, AppAdminBundle:Order]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Сформированные заказы"}

    app.admin.waiting_for_departure_orders:
        class: AppAdminBundle\Admin\WaitingForDepartureOrdersAdmin
        arguments: [~, AppBundle\Entity\Orders, AppAdminBundle:Order]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Заказы ожидающие отправки"}

    app.admin.sent_orders:
        class: AppAdminBundle\Admin\SentOrdersAdmin
        arguments: [~, AppBundle\Entity\Orders, AppAdminBundle:Order]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Отправленые заказы"}

    app.admin.canceled_orders:
        class: AppAdminBundle\Admin\CanceledOrdersAdmin
        arguments: [~, AppBundle\Entity\Orders, AppAdminBundle:Order]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Отмененые заказы"}

    app.admin.done_orders:
        class: AppAdminBundle\Admin\CanceledOrdersAdmin
        arguments: [~, AppBundle\Entity\Done, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Исполненые заказы"}

    app.admin.order_product_size:
        class: AppAdminBundle\Admin\OrderProductSizeAdmin
        arguments: [~, AppBundle\Entity\OrderProductSize, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    app.admin.cart:
        class: AppAdminBundle\Admin\CartAdmin
        arguments: [~, AppBundle\Entity\Cart, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Список всех заказанных товаров"}

    app.admin.categories:
        class: AppAdminBundle\Admin\CategoriesAdmin
        arguments: [~, AppBundle\Entity\Categories, AppAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Категории"}

    app.admin.filters:
        class: AppAdminBundle\Admin\FiltersAdmin
        arguments: [~, AppBundle\Entity\Filters, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Фильтры"}

    app.admin.products:
        class: AppAdminBundle\Admin\ProductsAdmin
        arguments: [~, AppBundle\Entity\Products, AppAdminBundle:CRUD, @service_container]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Модели"}
        calls:
            - [ setTemplate, [edit, AppAdminBundle:admin:product_models_edit.html.twig]]
            - [ setTranslationDomain, [AppAdminBundle]]

    app.admin.product_models:
        class: AppAdminBundle\Admin\ProductModelsAdmin
        arguments: [~, AppBundle\Entity\ProductModels, AppAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Товары"}
        calls:
            - [ addChild, [@app.admin.product_model_images] ]
            - [ setTemplate, [form, AppAdminBundle:admin:form_admin_fields.html.twig]]
            - [ setTemplate, [edit, AppAdminBundle:admin:product_models_edit.html.twig]]
            - [ setTranslationDomain, [AppAdminBundle]]

    app.admin.product_model_images:
        class: AppAdminBundle\Admin\ProductModelImagesAdmin
        arguments: [~, AppBundle\Entity\ProductModelImage, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Меню", label: "Изображения товаров", show_in_dashboard: false}

    app.admin.product_model_specific_size:
        class: AppAdminBundle\Admin\ProductModelSpecificSizeAdmin
        arguments: [~, AppBundle\Entity\ProductModelSpecificSize, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    app.admin.cities:
        class: AppAdminBundle\Admin\CitiesAdmin
        arguments: [~, AppBundle\Entity\Cities, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    app.admin.stores:
        class: AppAdminBundle\Admin\StoresAdmin
        arguments: [~, AppBundle\Entity\Stores, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    app.admin.characteristics:
        class: AppAdminBundle\Admin\CharacteristicsAdmin
        arguments: [~, AppBundle\Entity\Characteristics, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Характеристики"}

    app.admin.characteristic_values:
        class: AppAdminBundle\Admin\CharacteristicValuesAdmin
        arguments: [~, AppBundle\Entity\CharacteristicValues, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Значения характеристик"}

    app.admin.product_colors:
        class: AppAdminBundle\Admin\ProductColorsAdmin
        arguments: [~, AppBundle\Entity\ProductColors, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Цвета товаров"}

    app.admin.product_model_sizes:
        class: AppAdminBundle\Admin\ProductModelSizesAdmin
        arguments: [~, AppBundle\Entity\ProductModelSizes, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Размеры товаров"}

    app.admin.vendors:
        class: AppAdminBundle\Admin\VendorsAdmin
        arguments: [~, AppBundle\Entity\Vendors, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Магазин", label: "Поставщики", show_in_dashboard: false}

    app_admin.admin.main_slider:
        class: AppAdminBundle\Admin\MainSliderAdmin
        arguments: [~, AppBundle\Entity\MainSlider, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление сайтом", label: "Слайдер главной страницы"}

    app.admin.pages:
        class: AppAdminBundle\Admin\PageAdmin
        arguments: [~, AppBundle\Entity\Pages, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Управление сайтом", label: "Статические страницы" }

    app.admin.site_params:
        class: AppAdminBundle\Admin\SiteParamsAdmin
        arguments: [~, AppBundle\Entity\SiteParams, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление сайтом", label: "Параметры"}

    app.admin.call_back:
        class: AppAdminBundle\Admin\CallBackAdmin
        arguments: [~, AppBundle\Entity\CallBack, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Запросы на перезвон"}

    app.admin.menu:
        class: AppAdminBundle\Admin\MenuAdmin
        arguments: [~, AppBundle\Entity\Menu, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Меню", label: "Меню"}

    app.admin.menu_items:
        class: AppAdminBundle\Admin\MenuItemsAdmin
        arguments: [~, AppBundle\Entity\MenuItems, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Меню", label: "Элементы меню"}

    app.admin.import:
        class: AppAdminBundle\Admin\ImportAdmin
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@validator"]

    app.admin.block.import:
        class: AppAdminBundle\Block\ImportBlockService
        arguments: [ "app.admin.block.import:", @templating ]
        tags:
            - { name: sonata.block }

    app_admin.admin.main_banners:
        class: AppAdminBundle\Admin\MainBannersAdmin
        arguments: [~, AppBundle\Entity\MainBanners, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление сайтом", label: "Банеры главной страницы"}

    app_admin.admin.order_status:
        class: AppAdminBundle\Admin\OrderStatusAdmin
        arguments: [~, AppBundle\Entity\OrderStatus, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Статусы заказов"}

    app_admin.admin.order_status_pay:
        class: AppAdminBundle\Admin\OrderStatusPayAdmin
        arguments: [~, AppBundle\Entity\OrderStatusPay, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Управление заказами", label: "Статусы оплаты заказов"}

    app_admin.admin.price_list:
        pattern:  /admin/app/price-list
        class: AppAdminBundle\Admin\PriceListAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Магазин", label: "Прайс" }
        arguments: [~, AppBundle\Entity\ProductModelSpecificSize, SonataAdminBundle:CRUD]

    sonata.user.editable_role_builder:
        class:     AppAdminBundle\Security\EditableRolesBuilder
        arguments: [@security.context, @sonata.admin.pool, %security.role_hierarchy.roles%]

    sonata.user.form.type.security_roles:
        class:     AppAdminBundle\Form\Type\SecurityRolesType
        arguments: [@sonata.user.editable_role_builder, @translator]
        tags:
            - { name: form.type, alias: sonata_security_roles }

    sonata.user.form.type.stores_list:
        class:     AppAdminBundle\Form\Type\SonataStoresListType
        tags:
            - { name: form.type, alias: sonata_stores_list }
