
upload_file:
    path:     /upload-file
    defaults: { _controller: AppAdminBundle:Upload:uploadFile }
    options:
        expose: true

search_by_ttn:
    path:     /admin/app/search-by-ttn
    defaults: { _controller: AppAdminBundle:NovaPoshta:getWaybillInfo }
    options:
        expose: true

img_sorting:
    path:     /img-sorting
    defaults: { _controller: AppAdminBundle:Upload:sortProductModelsImages}
    options:
        expose: true

admin_app_import_index:
    pattern:  /admin/app/import
    defaults: { _controller: AppAdminBundle:Import:index}

admin_app_import_start:
    pattern:  /admin/app/import/start
    defaults: { _controller: AppAdminBundle:Import:start}

comur_image:
    resource: "@ComurImageBundle/Resources/config/routing.yml"
    prefix:   /